server:
  port: 0

spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/customerDB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true