server:
  port: 0

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/customerDB

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

test:
  name: Saman Kumara